### ISSUE TITLE
rw4 model save error

### ISSUE THREAD

**Issue by Splitwirez** [emd4600/SporeModder-FX#13]
Having trouble saving my changes to a rw4 model in SporeModderFX after altering a few compiled states. Error is as follows:
```java.lang.NegativeArraySizeException
	at emord.filestructures.FileStream.writePadding(FileStream.java:46)
	at sporemodder.file.rw4.RenderWare.writeAlignment(RenderWare.java:91)
	at sporemodder.file.rw4.RenderWare.write(RenderWare.java:131)
	at sporemodder.view.editors.RWModelViewer.saveData(RWModelViewer.java:1083)
	at sporemodder.view.editors.AbstractEditableEditor.lambda$3(AbstractEditableEditor.java:160)
	at sporemodder.UIManager.tryAction(UIManager.java:632)
```

Not sure if the SporeModder Blender addon or SporeModder FX itself is to blame. Here is the affected rw4 model and the blender project which produced it.
[ve_DI_spikeChest_01.zip](https://github.com/emd4600/SporeModder-FX/files/3659402/ve_DI_spikeChest_01.zip)

**Comment by emd4600** [comment]
How can I reproduce it?
